#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc --no-header -cp src/index.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -c -b > dist/index.min.js
echo "done."

rm -rf web/static/assets/lib/@plotdb/sandbox.js/dev/
mkdir -p web/static/assets/lib/@plotdb/sandbox.js/dev/
cp dist/* web/static/assets/lib/@plotdb/sandbox.js/dev/
